'use client'
import { DemoStore } from './types'

export const demoSeed: DemoStore = {
projects:[{id:'p1',name:'Airport Road Expansion',code:'ARE-01',location:'Accra',status:'active',start_date:'2026-01-01'},{id:'p2',name:'North Bridge Repair',code:'NBR-02',location:'Kumasi',status:'active',start_date:'2026-02-15'}],
suppliers:[{id:'s1',name:'Atlas Plant Hire',contact_email:'ops@atlas.demo',phone:'+233555001',address:'Industrial Area',status:'active'},{id:'s2',name:'Kofi Heavy Equipment',contact_email:'dispatch@kofi.demo',phone:'+233555002',address:'Tema Port Rd',status:'active'},{id:'s3',name:'BlueRock Rentals',contact_email:'team@bluerock.demo',phone:'+233555003',address:'Spintex',status:'active'}],
plants:[{id:'pl1',name:'CAT 320 Excavator',plant_code:'AT-EX-01',category:'Excavator',supplier_id:'s1',unit_type:'hour',status:'available'},{id:'pl2',name:'Volvo A40 Dumper',plant_code:'AT-DM-02',category:'Dumper',supplier_id:'s1',unit_type:'hour',status:'in_use'},{id:'pl3',name:'JCB Backhoe',plant_code:'KF-BH-11',category:'Backhoe',supplier_id:'s2',unit_type:'hour',status:'available'},{id:'pl4',name:'Komatsu Grader',plant_code:'KF-GR-09',category:'Grader',supplier_id:'s2',unit_type:'hour',status:'maintenance'},{id:'pl5',name:'Bobcat Skid',plant_code:'BR-SK-07',category:'Skid',supplier_id:'s3',unit_type:'hour',status:'available'},{id:'pl6',name:'CAT D6 Dozer',plant_code:'AT-DZ-08',category:'Dozer',supplier_id:'s1',unit_type:'hour',status:'in_use'},{id:'pl7',name:'Roller 10T',plant_code:'BR-RL-03',category:'Roller',supplier_id:'s3',unit_type:'hour',status:'available'},{id:'pl8',name:'Crane 30T',plant_code:'KF-CR-15',category:'Crane',supplier_id:'s2',unit_type:'hour',status:'available'}],
rates:[{id:'r1',supplier_id:'s1',plant_id:'pl1',project_id:'p1',rate_type:'hourly',hourly_rate:120,currency:'USD',effective_from:'2026-01-01'},{id:'r2',supplier_id:'s1',plant_id:'pl2',rate_type:'hourly',hourly_rate:140,currency:'USD',effective_from:'2026-01-01'},{id:'r3',supplier_id:'s2',plant_id:'pl3',rate_type:'hourly',hourly_rate:95,currency:'USD',effective_from:'2026-01-01'},{id:'r4',supplier_id:'s3',plant_id:'pl5',rate_type:'hourly',hourly_rate:85,currency:'USD',effective_from:'2026-01-01'}],
logs:[{id:'l1',date:'2026-05-01',project_id:'p1',supplier_id:'s1',plant_id:'pl1',hours_worked:8,idle_hours:1,breakdown_hours:0,description:'Excavation',status:'approved'},{id:'l2',date:'2026-05-02',project_id:'p1',supplier_id:'s1',plant_id:'pl2',hours_worked:9,idle_hours:0,breakdown_hours:0,description:'Hauling',status:'submitted'},{id:'l3',date:'2026-05-03',project_id:'p2',supplier_id:'s2',plant_id:'pl4',hours_worked:3,idle_hours:4,breakdown_hours:1,description:'Blade issue',status:'rejected',rejection_comment:'Need clearer note'},{id:'l4',date:'2026-05-04',project_id:'p1',supplier_id:'s3',plant_id:'pl7',hours_worked:7,idle_hours:1,breakdown_hours:0,description:'Compaction',status:'draft'},{id:'l5',date:'2026-04-18',project_id:'p1',supplier_id:'s1',plant_id:'pl1',hours_worked:6,idle_hours:0,breakdown_hours:0,description:'Old approved log',status:'included_in_ipc'}],
approvals:[{id:'a1',log_id:'l5',action:'approved',at:'2026-04-19T08:00:00Z'}],
ipcs:[{id:'i1',number:'IPC-2026-0001',project_id:'p1',supplier_id:'s1',start_date:'2026-04-01',end_date:'2026-04-30',status:'finalized',subtotal:720,total:720,line_ids:['il1']}],
ipcLines:[{id:'il1',log_id:'l5',date:'2026-04-18',plant_id:'pl1',hours:6,rate:120,amount:720}],
team:[{id:'u1',name:'Owner User',email:'owner@example.com',role:'owner'},{id:'u2',name:'Manager User',email:'manager@example.com',role:'manager'},{id:'u3',name:'Clerk User',email:'clerk@example.com',role:'site_clerk'},{id:'u4',name:'Supplier User',email:'supplier@example.com',role:'supplier',supplier_id:'s1'}]
}

const KEY='plantops-demo-store-v1'
export const loadStore=():DemoStore=>{ if(typeof window==='undefined') return demoSeed; const raw=localStorage.getItem(KEY); return raw?JSON.parse(raw):demoSeed }
export const saveStore=(s:DemoStore)=>{ localStorage.setItem(KEY,JSON.stringify(s)) }
export const makeId=(p:string)=>`${p}-${Math.random().toString(36).slice(2,8)}`
